# Jekyll configuration

name: Automating For The People
description: Automation/Cloud/DevOps, by Henry Buckle

# url is currently only used only for the RSS feed in feed.xml
url: https://hbuckle.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''
## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "en" 

paginate: 10

comments: true

highlighter: rouge
markdown: kramdown
plugins:
  - jekyll-paginate

exclude: ['README.md', 'LICENSE', "*.bak"]
